name: First Workflow
on: workflow_dispatch  #trigger which allow us to manually start the workflow
jobs: 
  first-job:    #this is a job name we can use anything
    runs-on: ubuntu-latest   # this is a reserved name this should be like this 
    steps:
      - name: print greeting
        run: |
          echo "Hello World"
          echo "completed the print greetings step"                 #define the command that should be executed to the command line
      - name: print Goodbye
        run: |
          echo "we are done !"
          echo "completed the print Goodbye step"
